[package]
name = "stretch"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]
test = false
doctest = false
bench = false

[dependencies]
pebble_rust_2026 = { git = "https://github.com/cmbartschat/pebble-rust-2026.git", rev = "fc73bf542bb7f8712b3e032797c2ef8035810f62" }

[profile.release]
panic = "abort"
opt-level = 2

[profile.dev]
panic = "abort"
