[package]
name = "stretch"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]
test = false
doctest = false
bench = false

[dependencies]
pebble_rust_2026 = { git = "https://github.com/cmbartschat/pebble-rust-2026.git", rev = "97b143e3a27932933a75cc661b031f8696f63ddc" }

[profile.release]
panic = "abort"
opt-level = 2

[profile.dev]
panic = "abort"
