const TRANSITION_DURATION_MILLIS: u64 = 1000;
pub const FRAME_TIME: u64 = 25;

pub const TIME_SCALE: i32 = 100;
pub const MAX_TIME: i32 = 30 * TIME_SCALE;
pub const TIME_STEP: i32 = MAX_TIME / (TRANSITION_DURATION_MILLIS / FRAME_TIME) as i32;
